export const SQS_MESSAGE_RECEIVED_HANDLER = Symbol.for(
  'SQS_MESSAGE_RECEIVED_HANDLER',
);

export const SQS_MESSAGE_PROCESSED_HANDLER = Symbol.for(
  'SQS_MESSAGE_PROCESSED_HANDLER',
);

export const SQS_MESSAGE_PROCESSING_ERROR_HANDLER = Symbol.for(
  'SQS_MESSAGE_PROCESSING_ERROR_HANDLER',
);
